# Generated by Django 2.2.6 on 2019-10-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atracao', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('horario_func', models.TextField()),
                ('idade_minima', models.IntegerField()),
                ('data', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
